config/routes.rb
TrafikskolaApp::Application.routes.draw do
	
  resources :schools, :path => "trafikskola" do
    member do 
      put 'submit'
    end
    resources :reviews
  end    
  root to: 'static_pages#home'

  match 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  # faceboook omniauth login/signout
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'auth/signout', to: 'sessions#destroy', as: 'signout'
end

app/models/school.rb
class School < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history] 
  
  has_many :reviews
  has_one :price
  has_one :likes
  has_one :checkin

  scope :by_score,   :joins => :reviews, :group => "schools.id", :order => "AVG(reviews.rating) DESC"
  scope :by_likes,   :joins => :likes,   :group => "schools.id", :order => "AVG(likes.fan_count) DESC"
  scope :by_desc,    :joins => :reviews, :group => "schools.id", :order => "DESC"
    
  include Tire::Model::Search
  include Tire::Model::Callbacks


  def self.search(params)
    params[:sort] ||= 'asc'
    tire.search(load: true, page: params[:page], per_page: 7) do 
      query { string params[:query] } if params[:query].present?
      sort { by :paket_pris, params[:sort] }
    end
  end

  def to_indexed_json
    to_json(methods: [:paket_pris])
  end

  def paket_pris
    price.paket_pris
  end

  # Beräknar medelvärdet för alla recensioner
  def avgerage_review_rating
  	return nil if reviews.blank?
  	reviews.average(:rating)
  end

  def count_reviews
  	reviews.count
  end

  def latest_reviews
    Review.joins(:school, :user).select("content, rating, schools.name, users.name").limit(2) 
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  
  # show method
  def show
    @school = School.find(params[:id])
  end

  # Index
  def index
    @schools = School.search(params)
  end

end

app/helpers/school_helper.rb
module SchoolHelper

	def format_rating(n)
		n.andand.round(1)
	end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_addreviews.html.erb
<% if user_signed_in? %>
    <div class="reviews">
    <%= form_for [@school, Review.new] do |f| %>
        <h3>Recensera detta trafikskola</h3>
        <div class="reviews_comments_container">
            <div class="review_box">
                <span id="betyg">Ange ett betyg (1-5) </span>
                <ol class="radio-rater">
                    <%= f.radio_button(:rating, 1) %>
                    <%= f.radio_button(:rating, 2) %>
                    <%= f.radio_button(:rating, 3) %>
                    <%= f.radio_button(:rating, 4) %>
                    <%= f.radio_button(:rating, 5) %>
                </ol>
            </div>
            <div class="review_box" id="review_textarea">
                <%= f.text_area :content, rows: 4, cols: 70, placeholder: "Skriv en kort recension..." %>
            </div>
            <div class="review_box">
                <%= f.submit 'Spara din recension', :class => "btn" %>
            </div>
        </div>
    <% end %>
<% else %>
    <p><a href="#">Logga in med facebook för att skriva recensioner</a></p>
<% end %>
    </div>

app/views/schools/_metainfo.html.erb
<div class="schoolrating">
	<ul>
			<li class="ratingtext">Betyg</li>
		<% if @school.reviews.any? %>
			<li class="ratingvalue"><%= format_rating(@school.avgerage_review_rating) %></li>
		<% else %>
			<li class="ratingvalue">0</li>
		<% end %>
			<li class="ratingantal"> <%= @school.count_reviews %> recensioner</li>
	</ul>
</div>
<div class="metainfo">
	<ul>
		<li>
			<%= image_tag('location.png') %>
			<p>
				<a href="#"><%= @school.locality %></a>
			</p>
		</li>
		<li>
			<%= image_tag('phone.png') %> 
			<p>
				<%= @school.tfn %>
			</p>
		</li>
		<li>
			<%= image_tag('globe.png') %>
			<p>
				<a href="<%= @school.url %>">Besök webbplats</a>
			</p>
		</li>
	</ul>
</div>

app/views/schools/_review_form.html.erb
        <%= form_for [@school, Review.new] do |f| %>
            <div class="reviews_comments_container">
                <h3>Testat det? Berätta vad du tycker om <%= @school.name %></h3>
                <div class="review_box rec1">
                    <label class="input-check ch1">
                        <input id="#rb1" type="radio" value="1"   name="review[rating]" /> Dåligt
                    </label>
                    <label class="input-check ch2">
                        <input id="#rb2" type="radio" value="2"   name="review[rating]" /> Acceptabelt
                    </label>
                    <label class="input-check ch3">
                        <input id="#rb3" type="radio" value="3"   name="review[rating]" /> Bra
                    </label>
                    <label class="input-check ch4">
                        <input id="#rb4" type="radio" value="4"   name="review[rating]" /> Mycket bra
                    </label>
                    <label class="input-check ch5">
                        <input id="#rb5" type="radio" value="5"   name="review[rating]" /> Utmärkt
                    </label>
                </div>
                    <div class="review_box rec2">
                        <%= f.text_area :content, rows: 1, cols: 70, placeholder: "Skriv några korta meningar om din upplevelse." %>
                        <%= f.hidden_field :school_id, :value => @school.id %>
                         <% if current_user %>
                            <%= f.submit 'Spara din rekommendation', :class => "btn" %>
                         <% else %>
                            <%= f.submit 'Registrera mig via Facebook & spara min rekommendation', :class => "btn" %>
                        <% end %>
                    </div>
                    
            </div>
        <% end %>
    <% else %>

app/views/schools/_review_medialist.html.erb
<div class="tabbable"> <!-- Only required for left/right tabs -->
        
    <div class="tab-content">
<% if @school.reviews.any? %>
    <% @school.reviews.each do |review| %>
    <ul class="media-list">
        <li class="media">
            <a class="pull-left" href="#">
                <%= image_tag(review.user.image, :alt => review.user.name, :class => "media-object img-rounded") %> 
            </a>
            <div class="media-body">
                <h4 class="media-heading"><%= link_to review.user.name, review.user.urls %>  </h4>
                <% if review.rating == 1 %>
                    <h4 class="recotext">är besviken</h4>
                    <div class="bravo">
                        <span class="betyg star selected"></span>
                        <span class="betyg emptystar selected"></span>
                        <span class="betyg emptystar selected"></span>
                        <span class="betyg emptystar selected"></span>
                        <span class="betyg emptystar selected"></span>

                    </div>
                <% elsif review.rating == 2 %>
                    <h4 class="recotext">är inte nöjd</h4>
                    <div class="bravo">
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                        <span class="betyg emptystar selected"></span>
                        <span class="betyg emptystar selected"></span>
                        <span class="betyg emptystar selected"></span>
                    </div>
                <% elsif review.rating == 3 %>
                    <h4 class="recotext">är nöjd</h4>
                    <div class="bravo">
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                        <span class="betyg emptystar selected"></span>
                        <span class="betyg emptystar selected"></span>

                    </div>
                <% elsif review.rating == 4 %>
                    <h4 class="recotext">är mycket nöjd</h4>
                    <div class="bravo">
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                        <span class="betyg emptystar selected"></span>
                    </div>
                <% else review.rating == 5 %>
                    <h4 class="recotext">är super nöjd</h4>
                    <div class="bravo">
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                        <span class="betyg star selected"></span>
                    </div>

                <% end %>                    
                <p><%= review.content %></p>
                <span class="spantext"><%= l review.created_at, :format => :short %></span>
             </div>
        </li>
    </ul>
    <% end %>
<% else %>
    <h4 id="noreco">Inga rekommendationer än</h4>
<% end %>
</div>
</div>

app/views/schools/_reviews.html.erb
<div class="reviews">
     <div class="item_review">
        <%= render 'schools/review_form' %>
     </div>
    <%= render 'schools/review_medialist' %>
</div>

app/views/schools/_school.html.erb
    <!-- Prices -->
  <table class="table table-bordered">
    <tr class="grey">
      <th><h4>Priser</h4></th>
      <th></th>
    </tr>
    <tr>
      <td><span class="pricetext">40 minuter körlektion</span></td>
      <td><span class="price"><%= @school.price.min %> kr</span></td>
    </tr>
    <tr>
      <td><span class="pricetext">Litteratur och ev. inskrivningsavgift</span></td>
      <td><span class="price"><%= @school.price.littin %> kr</span></td>
    </tr>
    <tr>
      <td><span class="pricetext">Riskutbildning 1 (riskettan)</span></td>
      <td><span class="price"><%= @school.price.risk1 %> kr</span></td>
    </tr>
    <tr>
      <td><span class="pricetext">Riskutbildning 2 (halkan)</span></td>
      <td><span class="price"><%= @school.price.risk2 %> kr</span></td>
    </tr>
    <tr>
      <td><span class="pricetext">Hyra av bil vid uppkörning</span></td>
      <td><span class="price"><%= @school.price.hyrbil %> kr</span></td>
    </tr>
    <tr>
      <td><span class="pricetext">Körpaket inklusive kostnader för tillstånd och test</span></td>
      <td>
        <span class="price">
          <%= @school.price.paket_pris %> kr
        </span>
      </td>
    </tr>
  </table>
  <!-- Incheckningar -->
  <table class="table table-bordered">
    <tr class="grey">
      <th><h4>Facebook vänner</h4></th>
    </tr>
      <th>
        <div class="checkin_container">
        <%= image_tag('location_pin_off.png') %>
        <div class="checkin"> 
            <p>Har dina Facebook-vänner varit här?</p>
             <span class="checkin_count">
                  <% if @school.checkin %>
                   <% if current_user %>
                        <strong><%= @school.checkin.checkin_count %></strong> 
                        personer har checkat in på <%= school.name %></br>
                        <span class="checkin_count">Inga av dina vänner har varit här</span> 
                   <% else %>
                       <strong><%= @school.checkin.checkin_count %></strong> 
                       personer har checkat in på <%= school.name %></br>
                       <span class="checkin_count">För att se om någon av dina vänner varit här:</span>  
                       <p><%= link_to 'Logga in med Facebook', '/auth/facebook' %></p>
                   <% end %>
                  <% else %>
                       <strong>0</strong> 
                       personer har checkat in på <%= school.name %>
                  <% end %>
                   
              </span><br/>
        </div>
        </div>
      </th>
    </tr>
  </table>


  

app/views/schools/_showreviews.html.erb
<h2><%= @school.reviews.count %> RECENSIONER</h2>
    <% @school.reviews.each do |review| %>
        <div class="review_box">
            <p><strong><%= review.user_name %></strong>:</p>
            <p><%= review.content %></p>
            <%= image_tag(review.user_image, :alt => review.user_name) %>
                <em>
                    &mdash;
                    <strong><%= review.rating %> stjänor</strong>
                </em>
        </div>
    <% end %> 

app/views/schools/index.html.erb
<%
meta :title => "Trafikskolor #{params[:query]} | Hittatrafikskola.nu",
     :description => "trafikskolor i #{params[:query]}",
     :keywords => %w(trafikskola trafikskolor bilskolor körskolor körkort)
%>
<div class="span12">
	<div class="searchresults">	
		<h1>Trafikskolor i <%= params[:query] %> <span></span></h1>
		 <ul>
			<li>
				<span class="resCheck label">
					<%= link_to "Billigast i #{params[:query]}",
								"trafikskola?utf8=%E2%9C%93&query=#{params[:query]}&sort=asc", 
								:class => "resCheckLink", :method => "get" %>
				</span>
			</li>
			<li>
				<span class="resCheck label">
					<%= link_to "Dyrast i #{params[:query]}",
								"trafikskola?utf8=%E2%9C%93&query=#{params[:query]}&sort=desc",
								:class => "resCheckLink", :method => "get" %>
				</span>
			</li>
		</ul>
		<table class="table searchresults">
			<tr>
				<th><h3>Trafikskola</h3></th>
				<th><h3>Pris per timme</h3></th>
				<th><h3>Pris för körkortspaket</h3></th>
			</tr>
			<% @schools.each do |school| %>
				<tr>
					<td> 
						<h3><%= link_to school.name, school %></h3>
						<p><%= school.adress %></p>
					</td>
					<td>
						<h3>
							<span class="label pricespan prispertimme">
								<%= school.price.min %> kr
							</span>
						</h3>
					</td>
					<td>
						<h3>
							<span class="label pricespan prispaketspan"> 
								<%= school.price.paket_pris %> kr
							</span>
						</h3>
					</td>
				</tr>
			<% end %>
		</table>
		<div class="digg_pagination">
			<%= will_paginate @schools, :container => false, 
										:params => { :search_text => params[:search_text] },
										:previous_label => "Föregånde",
										:next_label => "Nästa" %>
		</div>
	</div>
</div>

app/views/schools/show.html.erb
<% content_for :head do %>
  <%= tag :meta, property: "fb:app_id", content: ENV["FACEBOOK_APP_ID"] %>
  <%= tag :meta, property: "og:site_name", content: "allatrafikskolor" %>
  <%= tag :meta, property: "og:type", content: "allatrafikskolor:driving_school" %>
  <%= tag :meta, property: "og:title", content: @school.name %>
  <%= tag :meta, property: "og:url", content: school_url(@school) %>
  <%= tag :meta, property: "og:image", content: request.protocol + request.host_with_port + image_path("logo.png") %>
<% end %>

<%
meta :title => " #{@school.name} | Hittatrafikskola.nu",
     :description => "#{@school.name}",
     :keywords => %w(trafikskola trafikskolor bilskolor körskolor körkort)
%>
<div class="span3">
	<h1><%= @school.name %></h1>
	<%= render 'schools/metainfo' %>
</div>
<div class="span9">
	<%= render @school %>
    <%= render 'schools/reviews' %>
</div>