config/routes.rb
TrafikskolaApp::Application.routes.draw do
	
  resources :schools, :path => "trafikskola" do
    member do 
      put 'submit'
    end
    resources :reviews
  end    
  root to: 'static_pages#home'

  match 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  # faceboook omniauth login/signout
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'auth/signout', to: 'sessions#destroy', as: 'signout'
end

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <nav>
          <ul class="nav pull-left">
            <%= form_tag schools_path, :method => :get, :class => "search_form" do %>
              <div class="input-prepend input-append">
                <%= text_field_tag :search, params[:search], :class => "search-query-large", :placeholder => "Sök ort eller trafikskola", :name => "search", :id => "appendedPrependedInput" %>
                 <!-- <span class="add-on"><%= link_to 'Sök', schools_path, :method => :get %></span -->                
                 <%= submit_tag "Sök", :name => nil, :class => "add-on" %>
              </div>
              <!-- <span class="search-help-block">Exempel: "Odenplan", "Holmgatan, Malmö" eller "Mårtensson trafikskola"</span> -->
            <% end %>
          </ul>
          <ul class="nav pull-right">
              <% if user_signed_in? %>

               <!-- <li><%= link_to 'Edit profile', edit_user_registration_path %></li> -->
                <li><%= link_to "Logga ut", destroy_user_session_path, method: :delete %></li>
                <li><a class="active_menu" href="#"><%= current_user.name %></a></li>
              <% else %>
                <!-- <li><%= link_to "Bli medlem", new_user_registration_path %></li>
                <li><%= link_to "Logga in", new_user_session_path %></li> -->
                <li><%= link_to '<i class="icon-user icon-white"></i> Logga in med facebook'.html_safe, 
                        user_omniauth_authorize_path(:facebook), :class => "active_menu"  %></li>
              <% end %>
         </ul>
       </nav>
     </div>
   </div>
 </header>

app/views/layouts/_msg.html.erb
<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>

app/views/layouts/_newheader.html.erb
<header id="header">
  <div class="container">
    <%= link_to(image_tag('logo_small.png'), root_path) %>
    <h1 class="sitename"><%= link_to "hittatrafikskola.nu", root_path %></h1>
        <nav>
          <ul class="nav pull-left">
           <li>
            <%= form_tag schools_path, :method => :get, :class => "search_form" do %>
              <div class="input-prepend input-append">
                <%= text_field_tag :query, params[:query], 
                                   :class => "search-query-large", 
                                   :placeholder => "Sök ort eller trafikskola", 
                                   :name => "query", :id => "appendedPrependedInput" 
                %>
                 <%= submit_tag "Sök", :name => nil, :class => "add-on" %>
              </div>
            <% end %>
           </li>
          </ul>
          <ul class="pull-right">
            <% if current_user %>
              <li><strong>Hej, <%= current_user.name %></strong></li>
              <li><%= link_to "Logga ut", signout_path, id: "sign_out" %></li>
            <% else %>
              <li>
                <div class="facebook_inloggning">
                  <%= image_tag('facebook_small.png') %>
                  <%= link_to "Logga in med facebook", "/auth/facebook", id: "sign_in" %>
                </div>
              </li>
            <% end %>
          </ul>
       </nav>
</header>

app/views/layouts/_pageheader.html.erb
<!-- <div class="page-header">
	<form class="form">
		<label class="search-label">Sök område eller trafikskola</label>
		<input type="text" class="input-medium search-query-large">
		<button type="submit" class="btn btn-large">Sök</button>
		<span class="search-help-block">Exempel: "Odenplan", "Holmgatan, Malmö" eller "Mårtensson trafikskola"</span>
	</form>
</div> 
<div class="page-header">
	<%= form_tag schools_path, :method => :get do %>
		<label class="search-label">Sök område eller trafikskola</label>
		<%= text_field_tag :search, params[:search], :class => "input-medium search-query-large" %>
		<%= submit_tag "Sök", :name => nil, :class => "btn btn-large" %>
		<span class="search-help-block">Exempel: "Odenplan", "Holmgatan, Malmö" eller "Mårtensson trafikskola"</span>
	<% end %>
</div>
-->

app/views/layouts/_search.html.erb
<!-- Search bar -->
<div class="row search-bar">
	<div class="span12 search-padding">
		<form class="form-search">
			<h3>Sök områden eller trafikskola</h3>
			<input type="text" class="input-medium search-query">
			<button type="submit" class="btn">Sök</button>
		</form>
	</div>
</div>

app/views/layouts/_shim.html.erb
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39622662-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= metamagic %>
	<%= stylesheet_link_tag("application")%>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= yield :head %>
</head>
<body>
	<%= render 'layouts/newheader' %>
	<div class="container">
		<div class="content">
			<%= render 'layouts/msg' %>
			<div class="row">
				<%= yield %>
			</div>
		</div>
	</div>
	<%= render 'layouts/shim' %>
</body>
</html>	